export const products = [
  {
    id: 'p1',
    name: 'Copilot Hoodie',
    price: 54.99,
    category: 'apparel',
    image: 'https://placehold.co/300x300?text=Hoodie',
    description: 'Soft fleece hoodie with embroidered GitHub Copilot logo.',
  },
  {
    id: 'p2',
    name: 'Octocat Plush',
    price: 19.99,
    category: 'toys',
    image: 'https://placehold.co/300x300?text=Octocat',
    description: 'Collectible plush Octocat, perfect for your desk.',
  },
  {
    id: 'p3',
    name: 'Mechanical Keyboard',
    price: 129.0,
    category: 'electronics',
    image: 'https://placehold.co/300x300?text=Keyboard',
    description: 'Hot-swappable mechanical keyboard for late-night shipping.',
  },
  {
    id: 'p4',
    name: 'Sticker Pack: Azure Edition',
    price: 6.5,
    category: 'accessories',
    image: 'https://placehold.co/300x300?text=Stickers',
    description: 'Laptop-ready vinyl stickers featuring Azure services.',
  },
  {
    id: 'p5',
    name: 'Insulated Mug',
    price: 22.0,
    category: 'accessories',
    image: 'https://placehold.co/300x300?text=Mug',
    description: 'Keeps your coffee hot through the whole deploy pipeline.',
  },
  {
    id: 'p6',
    name: 'Wireless Mouse',
    price: 39.5,
    category: 'electronics',
    image: 'https://placehold.co/300x300?text=Mouse',
    description: 'Ergonomic wireless mouse with silent clicks.',
  },
];
